FROM python:3.9.4
## Install dependencies
RUN apt-get update \    
    # Create basic project structure
    && mkdir -p /code/

WORKDIR /code

ADD project/requirements.txt requirements.txt
RUN pip install -r requirements.txt --no-cache-dir


EXPOSE 7777